import PptxGenJS from "pptxgenjs";

interface EvidenceSlide {
  manuscriptSentence: string;
  manuscriptSection: string | null;
  supportingPassage: string;
  paperTitle: string;
  paperAuthors: string;
  paperYear: number | null;
  paperSection: string | null;
  paperPage: number | null;
  doi: string | null;
  pdfUrl?: string | null;
  confidence: number;
  rationale: string | null;
  humanVerified: boolean;
  verifiedBy: string | null;
  verifiedAt: Date | null;
}

export async function renderEvidencePptx(
  documentTitle: string,
  slides: EvidenceSlide[],
): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.title = `Evidence Documentation: ${documentTitle}`;
  pptx.author = "Unmute AI";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText("Evidence Documentation", {
    x: 0.5,
    y: 1.5,
    w: 9,
    h: 1,
    fontSize: 28,
    bold: true,
    align: "center",
    color: "1a1a2e",
  });
  titleSlide.addText(documentTitle, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 0.8,
    fontSize: 18,
    align: "center",
    color: "555555",
  });
  titleSlide.addText(
    `${slides.length} citations mapped | ${slides.filter((s) => s.humanVerified).length} verified`,
    {
      x: 0.5,
      y: 3.5,
      w: 9,
      h: 0.5,
      fontSize: 14,
      align: "center",
      color: "888888",
    },
  );
  titleSlide.addText(
    `Generated by Unmute AI | ${new Date().toLocaleDateString()}`,
    {
      x: 0.5,
      y: 5,
      w: 9,
      h: 0.3,
      fontSize: 10,
      align: "center",
      color: "aaaaaa",
    },
  );

  // Evidence slides
  for (const [index, evidence] of slides.entries()) {
    const slide = pptx.addSlide();

    // Header: slide number
    slide.addText(`Evidence ${index + 1} / ${slides.length}`, {
      x: 0.3,
      y: 0.1,
      w: 9.4,
      h: 0.3,
      fontSize: 9,
      color: "888888",
      align: "right",
    });

    // Manuscript claim
    slide.addText("Manuscript Claim", {
      x: 0.3,
      y: 0.4,
      w: 9.4,
      h: 0.3,
      fontSize: 10,
      bold: true,
      color: "1a1a2e",
    });
    slide.addText(`"${evidence.manuscriptSentence}"`, {
      x: 0.3,
      y: 0.7,
      w: 9.4,
      h: 0.8,
      fontSize: 12,
      italic: true,
      color: "333333",
      valign: "top",
    });
    if (evidence.manuscriptSection) {
      slide.addText(`Section: ${evidence.manuscriptSection}`, {
        x: 0.3,
        y: 1.5,
        w: 4,
        h: 0.25,
        fontSize: 9,
        color: "666666",
      });
    }

    // Divider
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.3,
      y: 1.8,
      w: 9.4,
      h: 0.02,
      fill: { color: "cccccc" },
    });

    // Supporting evidence
    slide.addText("Supporting Evidence", {
      x: 0.3,
      y: 1.9,
      w: 9.4,
      h: 0.3,
      fontSize: 10,
      bold: true,
      color: "1a6b3a",
    });
    slide.addText(`"${evidence.supportingPassage}"`, {
      x: 0.3,
      y: 2.2,
      w: 9.4,
      h: 1.2,
      fontSize: 11,
      color: "333333",
      valign: "top",
      fill: { color: "f0f9f4" },
    });

    // Paper metadata
    const authorYear = `${evidence.paperAuthors} (${evidence.paperYear ?? "n.d."})`;
    slide.addText(authorYear, {
      x: 0.3,
      y: 3.5,
      w: 9.4,
      h: 0.3,
      fontSize: 10,
      bold: true,
      color: "333333",
    });
    slide.addText(evidence.paperTitle, {
      x: 0.3,
      y: 3.8,
      w: 9.4,
      h: 0.3,
      fontSize: 10,
      italic: true,
      color: "555555",
    });

    const metaLine = [
      evidence.paperSection ? `Section: ${evidence.paperSection}` : null,
      evidence.paperPage ? `Page: ${evidence.paperPage}` : null,
      evidence.doi ? `DOI: ${evidence.doi}` : null,
    ]
      .filter(Boolean)
      .join("  |  ");
    if (metaLine) {
      slide.addText(metaLine, {
        x: 0.3,
        y: 4.1,
        w: 9.4,
        h: 0.25,
        fontSize: 9,
        color: "777777",
      });
    }

    // PDF link
    if (evidence.pdfUrl) {
      slide.addText(`PDF: ${evidence.pdfUrl}`, {
        x: 0.3,
        y: 4.35,
        w: 9.4,
        h: 0.2,
        fontSize: 8,
        color: "4444cc",
        hyperlink: { url: evidence.pdfUrl },
      });
    }

    // Confidence and rationale
    const confidenceColor =
      evidence.confidence >= 0.7
        ? "1a6b3a"
        : evidence.confidence >= 0.4
          ? "b8860b"
          : "cc3333";
    slide.addText(
      `Confidence: ${(evidence.confidence * 100).toFixed(0)}%`,
      {
        x: 0.3,
        y: 4.5,
        w: 2,
        h: 0.25,
        fontSize: 10,
        bold: true,
        color: confidenceColor,
      },
    );

    if (evidence.rationale) {
      slide.addText(evidence.rationale, {
        x: 2.5,
        y: 4.5,
        w: 7.2,
        h: 0.25,
        fontSize: 9,
        color: "666666",
      });
    }

    // Verification status
    const verifiedText = evidence.humanVerified
      ? `Verified by ${evidence.verifiedBy ?? "reviewer"} on ${evidence.verifiedAt?.toLocaleDateString() ?? ""}`
      : "Not yet verified by human reviewer";
    const verifiedColor = evidence.humanVerified ? "1a6b3a" : "b8860b";
    slide.addText(verifiedText, {
      x: 0.3,
      y: 4.9,
      w: 9.4,
      h: 0.3,
      fontSize: 10,
      color: verifiedColor,
      bold: evidence.humanVerified,
    });
  }

  const buffer = await pptx.write({ outputType: "nodebuffer" });
  return Buffer.from(buffer as ArrayBuffer);
}
